using System.Text;
using DisCatSharp.ApplicationCommands;

namespace AGC_Management.Eventlistener;

[EventHandler]
public class OnApplyComponentInteraction : BaseCommandModule
{
    [Event]
    public async Task ComponentInteractionCreated(DiscordClient client, ComponentInteractionCreateEventArgs args)
    {
        _ = Task.Run(async () =>
            {
                string cid = args.Interaction.Data.CustomId;
                var values = args.Interaction.Data.Values;
                if (cid != "applypanelselector") return;
                var randomid = new Random();
                var ncid = randomid.Next(100000, 999999).ToString();
                DiscordInteractionModalBuilder modal = new();
                var pos = $"{values[0].ToString().Substring(0, 1).ToUpper()}{values[0].ToString().Substring(1)}";
                modal.WithTitle($"Bewerbung für ");
                modal.CustomId = cid;
                modal.AddTextComponent(new DiscordTextComponent(TextComponentStyle.Paragraph,
                    label: "Wieso möchtest du dich bewerben?", minLength: 10, maxLength: 500));    
                modal.AddTextComponent(new DiscordTextComponent(TextComponentStyle.Small,
                    label: "Deine Onlinezeiten bzw wann wärst du da?", minLength: 15, maxLength: 500, required: false, placeholder:"Geb hier wann und wieviel du Mitwirken kannst"));
                modal.AddTextComponent(new DiscordTextComponent(TextComponentStyle.Paragraph,
                    label: "Bewerbungstext", minLength: 100, maxLength: 3500, required: true, placeholder:"Geb hier deinen Bewerbungstext ein"));
                modal.CustomId = "bewerben_" + $"{pos}";
                

                
                await args.Interaction.CreateInteractionModalResponseAsync(modal);
                
            }
        );
        
        _ = Task.Run(async () =>
            {
                var cid = args.Interaction.Data.CustomId;
                if (!cid.StartsWith("bewerben_")) return;
                var why = args.Interaction.Data.Components[0].Value;
                var online = args.Interaction.Data.Components[1].Value;
                var value = args.Interaction.Data.Components[2].Value;
                var randomid = new Random();
                var ncid = randomid.Next(100000, 999999).ToString();
                var embed = new DiscordEmbedBuilder();
                var str = new StringBuilder();
                str.AppendLine("---- AUTOGENERATED FIELD (WIESO)----\n\n");
                str.AppendLine(why);
                str.AppendLine("\n\n---- AUTOGENERATED FIELD (ONLINEZEITEN)----\n\n");
                str.AppendLine(online);
                str.AppendLine("\n\n---- AUTOGENERATED FIELD (BEWERBUNGSTEXT)----\n\n");
                str.AppendLine(value);
                var str_as_base64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(str.ToString()));
                var position = cid.Split("_")[1];   
                embed.WithTitle("Bewerbung");
                embed.WithDescription("Deine Bewerbung wurde erfolgreich abgeschickt!");
                embed.WithColor(DiscordColor.Gold);
                
                var unixnow = DateTimeOffset.Now.ToUnixTimeSeconds();
                
                //                 "CREATE TABLE IF NOT EXISTS bewerbungen (bewerbungsid TEXT, userid BIGINT, positionname TEXT, status INTEGER DEFAULT 0, timestamp BIGINT, bewerbungstext TEXT, seenby BIGINT[] DEFAULT '{}')"

                var db = CurrentApplication.ServiceProvider.GetRequiredService<NpgsqlDataSource>();
                await using var command = db.CreateCommand("INSERT INTO bewerbungen (bewerbungsid, userid, positionname, status, timestamp, bewerbungstext) VALUES (@bewerbungsid, @userid, @positionname, @status, @timestamp, @bewerbungstext)");
                command.Parameters.AddWithValue("bewerbungsid", $"{position}_{ncid}");
                command.Parameters.AddWithValue("userid", (long)args.User.Id);
                command.Parameters.AddWithValue("positionname", position);
                command.Parameters.AddWithValue("status", 0);
                command.Parameters.AddWithValue("timestamp", unixnow);
                command.Parameters.AddWithValue("bewerbungstext", str_as_base64);
                await command.ExecuteNonQueryAsync();
                
                
                
            }
        );
        
    }
}